defaults: &defaults
  docker:
    - image: 'circleci/node:12'
  working_directory: ~/project/vaken
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - vaken
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - 'dependency-cache-{{ checksum "package-lock.json" }}'
            - dependency-cache-
      - run: 'npm i --no-shrinkwrap && npm run generate' # might want to use ci for some sort of really aggressive pre-deploy test
      - save_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - vaken
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: 'npm run check:lint:ci'
      - store_test_results:
          path: ~/project/vaken/reports/lint
  typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: 'npm run check:types'
  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: 'npm audit --audit-level=high --only=prod'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: 'npm run check:test:ci'
      - store_test_results:
          path: ~/project/vaken/reports/test
      - codecov/upload:
          file: coverage/*.json
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: 'npm run build'

workflows:
  all:
    jobs:
      - setup
      - install:
          requires:
            - setup
      - audit:
          requires:
            - setup
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - build:
          requires:
            - install
