on: push
name: Make a draft PR onpush
jobs:
  makeDraftPr:
    name: make draft pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make draft pr
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: dev
          PULL_REQUEST_DRAFT: 'true'
